# -*- coding: utf-8 -*-
"""contracts_ocr_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvcG1Xduzg4NIggHEy622jLRwAmbvkoR

# الخلية 1: تثبيت المكتبات المطلوبة
"""

# تثبيت محرك Tesseract والحزمة العربية
!apt-get update -qq
!apt-get install -y -qq tesseract-ocr tesseract-ocr-ara
!pip install -q pytesseract

"""# الخلية 2: استيراد المكتبات"""

import os
import re
import json
import copy
import shutil
import io
from pathlib import Path
from datetime import datetime

import fitz  # PyMuPDF
from PIL import Image
import pytesseract
from tenacity import retry, stop_after_attempt, wait_exponential

from google.colab import files as colab_files

"""# الخلية 3: الإعدادات وعمل Client لـ Gemini"""

CONFIG = {
    "output_dir": "/content/output",
    "langs": ["ar", "eng"],
    "chunk_max_lines": 40,
    "chunk_overlap_lines": 3,
}
os.makedirs(CONFIG["output_dir"], exist_ok=True)

# قراءة مفتاح API لاستخدامه لاحقاً في مرحلة التحليل والـ RAG
try:
    api_key = userdata.get("GEMINI_API_KEY")
except Exception:
    api_key = os.environ.get("GEMINI_API_KEY")

if api_key:
    from google import genai
    client = genai.Client(api_key=api_key)
    print("تم تهيئة العميل للخطوات القادمة (التحليل/RAG) بنجاح.")
else:
    client = None
    print("تنبيه: لم يتم العثور على مفتاح API. الاستخراج المحلي سيعمل بشكل طبيعي، لكن سنحتاجه لاحقاً للتلخيص والـ RAG.")

STATE_FILE = os.path.join(CONFIG["output_dir"], "_pipeline_state.json")

def load_state():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_state(state):
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)

PIPELINE_STATE = load_state()
print("الإعدادات جاهزة. استكمال سابق موجود:", bool(PIPELINE_STATE))

"""# الخلية 4: رفع الملف وتحويله إلى صور (PDF -> Img)"""

# 1. ربط Google Drive وإنشاء مجلد الحفظ إن لم يكن موجوداً
drive.mount('/content/drive', force_remount=False)

DRIVE_DIR = "/content/drive/MyDrive/Contract_System"
os.makedirs(DRIVE_DIR, exist_ok=True)
DRIVE_CONTRACT_PATH = os.path.join(DRIVE_DIR, "original_contract.pdf")

print("رفع ملف العقد (PDF أو JPG أو JPEG أو PNG)...")
uploaded = colab_files.upload()
if not uploaded:
    raise RuntimeError("لم يتم رفع أي ملف.")

INPUT_FILENAME = list(uploaded.keys())[0]
INPUT_PATH = os.path.join("/content", INPUT_FILENAME)

with open(INPUT_PATH, "wb") as f:
    f.write(uploaded[INPUT_FILENAME])

CONFIG["source_file"] = INPUT_FILENAME
CONFIG["input_path"] = INPUT_PATH

def load_pages(input_path):
    """يحول الملف إلى صور PIL باستخدام PyMuPDF بسرعة ودقة عالية."""
    ext = Path(input_path).suffix.lower()
    pages = []

    if ext == ".pdf":
        doc = fitz.open(input_path)
        for page in doc:
            pix = page.get_pixmap(dpi=300)
            img = Image.open(io.BytesIO(pix.tobytes("png"))).convert("RGB")
            pages.append(img)
    elif ext in [".jpg", ".jpeg", ".png"]:
        pages = [Image.open(input_path).convert("RGB")]
    else:
        raise ValueError(f"صيغة غير مدعومة: {ext}")

    if not pages:
        raise ValueError("لم يتم استخراج أي صفحة.")
    return pages

# تحميل الصفحات من الملف المرفوع
PAGES = load_pages(INPUT_PATH)

# 2. حفظ النسخة التلقائية بـ Google Drive باسم original_contract.pdf
ext = Path(INPUT_PATH).suffix.lower()

if ext == ".pdf":
    # إذا كان الملف المرفوع PDF يتم نسخه مباشرةً وتجاوز القديم
    shutil.copyfile(INPUT_PATH, DRIVE_CONTRACT_PATH)
else:
    # إذا كان الملف صورة (JPG/PNG) يتم تحويله إلى PDF وحفظه بنفس الاسم
    PAGES[0].save(DRIVE_CONTRACT_PATH, "PDF", resolution=100.0)

print(f"\nتم رفع الملف وتحويله بنجاح! عدد الصفحات: {len(PAGES)}")
print(f"✅ تم حفظ نسخة تلقائية محدثة في Google Drive:")
print(f"📌 المسار: {DRIVE_CONTRACT_PATH}")

"""# الخلية 5: استخراج النصوص بـ Gemini (Ext)"""

import pytesseract

def extract_text_local_ocr(pages):
    """استخراج النصوص سطر بسطر محلياً باستخدام Tesseract بدون الحاجة لأي API."""
    raw_ocr_data = []

    # إعدادات Tesseract لقراءة اللغة العربية والإنجليزية
    custom_config = r'--oem 3 --psm 6'

    for page_idx, page_image in enumerate(pages):
        page_number = page_idx + 1
        print(f"جاري معالجة الصفحة {page_number} من {len(pages)} محلياً...")

        try:
            # استخراج النص من الصورة محلياً
            text = pytesseract.image_to_string(page_image, lang='ara+eng', config=custom_config)

            # تقسيم النص الناتج إلى أسطر وتنظيف الفراغات
            lines = [line.strip() for line in text.split('\n') if line.strip()]

            for line_idx, line_text in enumerate(lines):
                line_id = f"p{page_number}_l{line_idx + 1}"
                raw_ocr_data.append({
                    "page": page_number,
                    "line_id": line_id,
                    "line_number": line_idx + 1,
                    "text": line_text,
                    "confidence": 1.0,
                    "bbox": None
                })
        except Exception as e:
            print(f"⚠️ خطأ في معالجة الصفحة {page_number}: {e}")

    return raw_ocr_data

# تشغيل الاستخراج المحلي
print("تشغيل استخراج النصوص المحلي (Tesseract OCR)...")
raw_ocr_data = extract_text_local_ocr(PAGES)

if not raw_ocr_data:
    raise RuntimeError("لم يتم استخراج أي نص! تأكد من تثبيت tesseract-ocr وحزمة tesseract-ocr-ara.")

print(f"\n✅ تم الاستخراج بنجاح محلياً!")
print(f"إجمالي الأسطر المستخرجة: {len(raw_ocr_data)} عبر {len(PAGES)} صفحات.")

"""# الخلية 6: حفظ المخرجات الخام وحماية النسخة الأصلية (Immutable Object)"""

def save_raw_ocr(data, output_dir):
    """حفظ نتائج الـ OCR الخام في ملفات JSON و TXT"""
    raw_json_path = os.path.join(output_dir, "raw_ocr.json")
    with open(raw_json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    raw_txt_path = os.path.join(output_dir, "raw_ocr.txt")
    lines_by_page = {}
    for item in data:
        lines_by_page.setdefault(item["page"], []).append(item)

    with open(raw_txt_path, "w", encoding="utf-8") as f:
        for page in sorted(lines_by_page.keys()):
            f.write(f"===== صفحة {page} =====\n")
            for item in sorted(lines_by_page[page], key=lambda x: x["line_number"]):
                f.write((item["text"] or "") + "\n")
            f.write("\n")

    return raw_json_path, raw_txt_path

raw_json_path, raw_txt_path = save_raw_ocr(raw_ocr_data, CONFIG["output_dir"])
print(f"تم حفظ البيانات الخام بـ JSON في: {raw_json_path}")
print(f"تم حفظ النص المجمع بـ TXT في: {raw_txt_path}")

# نسخة محمية من البيانات الخام
RAW_OCR_IMMUTABLE = copy.deepcopy(raw_ocr_data)

"""# الخلية 7: تعديل وتنسيق النص عبر الـ LLM (Text Post-Processing)


"""

import os

def clean_and_format_by_page(ocr_data):
    """
    تجميع أسطر الـ OCR حسب رقم الصفحة، ثم إرسال كل صفحة مستقلة للـ LLM
    لتفادي الاقتطاع وضمان إخراج كافة الصفحات (1 إلى 4) بالكامل.
    """
    # 1. تجميع الأسطر حسب رقم الصفحة
    pages_dict = {}
    for item in ocr_data:
        pages_dict.setdefault(item["page"], []).append(item["text"])

    full_formatted_document = []

    print(f"بدء تنسيق وتدقيق {len(pages_dict)} صفحات عبر LLM صفحة بصفحة...\n")

    for page_num in sorted(pages_dict.keys()):
        lines = pages_dict[page_num]
        raw_page_text = "\n".join(lines)

        print(f"جاري تدقيق وتنسيق الصفحة {page_num} من {len(pages_dict)}...")

        prompt = f"""
أنت خبير تدقيق وتصحيح نصوص الـ OCR. أمامك النص الخام المستخرج من الصفحة رقم ({page_num}) من المستند.

المطلوب منك بدقة:
1. تصحيح الأخطاء الإملائية والمطبعية والكلمات المقطوعة الناتجة عن الـ OCR.
2. إعادة تنسيق النص بأسلوب مرتب ومقروء (عناوين، بنود، فقرات).
3. الحفاظ الكامل على جميع البيانات، الأسماء، الأرقام، والتواريخ دون اختصار أو حذف أي جزء.
4. ابدأ استجابتك مباشرة بـ "--- صفحة {page_num} ---" ثم اتبعها بالنص المنسق دون كتابة أي مقدمات أو شروحات.

النص الخام للصفحة {page_num}:
{raw_page_text}
        """

        try:
            response = client.models.generate_content(
                model="gemini-3.6-flash",
                contents=prompt
            )
            page_output = response.text.strip()
            full_formatted_document.append(page_output)
            print(f"✅ تم تنسيق الصفحة {page_num} بنجاح.")
        except Exception as e:
            print(f"❌ حدث خطأ أثناء معالجة الصفحة {page_num}: {e}")
            # في حال التعثر يُعتمد النص الخام للصفحة لتجنب فقدان البيانات
            full_formatted_document.append(f"--- صفحة {page_num} ---\n{raw_page_text}")

    # دمج كافة الصفحات في نص واحد شامل
    return "\n\n" + "\n\n".join(full_formatted_document)

# 2. تشغيل المعالجة
formatted_document_text = clean_and_format_by_page(RAW_OCR_IMMUTABLE)

# 3. حفظ المستند الكامل المنسق
formatted_output_path = os.path.join(CONFIG["output_dir"], "formatted_document.txt")
with open(formatted_output_path, "w", encoding="utf-8") as f:
    f.write(formatted_document_text)

# 4. تسليم النص المنسق كاملاً لمتغير الشات بوت
FINAL_CHATBOT_CONTEXT = formatted_document_text

print("\n==================================================")
print("🚀 اكتملت عملية التنسيق لكامل الصفحات الأربع بنجاح!")
print(f"إجمالي طول النص المنسق النهائي: {len(FINAL_CHATBOT_CONTEXT)} حرف.")
print(f"تم حفظ الملف المنسق كاملاً في: {formatted_output_path}")
print("==================================================")

"""# الخلية:8 النص النهائي المعدل"""

import os

formatted_output_path = os.path.join(CONFIG["output_dir"], "formatted_document.txt")

# قراءة واستعراض النص المنسق الكامل
if os.path.exists(formatted_output_path):
    with open(formatted_output_path, "r", encoding="utf-8") as f:
        full_text = f.read()

    print("==================================================")
    print("📜 عرض النص النهائي المنسق لجميع الصفحات:")
    print("==================================================\n")
    print(full_text)
    print("\n==================================================")
    print(f"📊 إجمالي حجم النص: {len(full_text)} حرف.")
    print("==================================================")
else:
    print("⚠️ لم يتم العثور على الملف المنسق. يرجى إعادة تشغيل خلية المعالجة والتنسيق أولاً.")