# -*- coding: utf-8 -*-
"""LegalLens_Contract_Chatbot_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjG7VF9b70BqE5g7bv0S-XpNVVw3vZbo

# LegalLens — Contract Chatbot (Final)

نسخة مبسطة ومتكاملة من الشات بوت تعتمد على **الملف الأصلي للعقد المحفوظ مسبقًا في Google Drive** كمصدر الحقيقة الوحيد.

لا يوجد رفع جديد للعقد، ولا يعتمد الشات بوت على ملف OCR في الإجابة. ملف OCR يمكن أن يظل موجودًا للمراجعة في مشروع الـ OCR، لكنه ليس مصدر الإجابات هنا.
"""

# 1) تثبيت المكتبات
!pip -q install -U google-genai ipywidgets PyMuPDF
print('✅ تم تجهيز المكتبات.')

# 2) Imports + API Key
import os
import time
import html
import mimetypes
import ipywidgets as widgets

from google.colab import drive, userdata
from google import genai
from google.genai import types
from IPython.display import display, HTML

# احصل على المفتاح من Colab Secrets باسم GEMINI_API_KEY
API_KEY = ''
try:
    API_KEY = userdata.get('GEMINI_API_KEY') or ''
except Exception:
    API_KEY = ''

API_KEY = API_KEY.strip()
if not API_KEY:
    raise RuntimeError(
        '❌ لم يتم العثور على GEMINI_API_KEY. أضف المفتاح في Colab Secrets باسم GEMINI_API_KEY ثم أعد تشغيل الخلية.'
    )

client = genai.Client(api_key=API_KEY)
print('✅ تم تجهيز Gemini API بنجاح.')

# 3) Drive + تحديد العقد الأصلي المحفوظ مسبقًا
drive.mount('/content/drive', force_remount=False)

# هذا هو نفس المسار المطلوب: لا تغيّره إذا كان العقد محفوظًا هنا
CONTRACT_PATH = '/content/drive/MyDrive/Contract_System/original_contract.pdf'

if not os.path.isfile(CONTRACT_PATH):
    raise FileNotFoundError(
        f'❌ لم يتم العثور على العقد الأصلي في المسار المحدد:\n{CONTRACT_PATH}'
    )

file_size_mb = os.path.getsize(CONTRACT_PATH) / (1024 * 1024)
print(f'✅ تم العثور على العقد الأصلي.')
print(f'📄 الاسم: {os.path.basename(CONTRACT_PATH)}')
print(f'📌 المسار: {CONTRACT_PATH}')
print(f'📦 الحجم: {file_size_mb:.2f} MB')

# 4) رفع العقد الأصلي إلى Gemini مرة واحدة فقط داخل جلسة Colab
#    مهم: هذا ليس رفعًا من المستخدم؛ الشات بوت يسحب الملف تلقائيًا من Drive.

SUPPORTED_MODELS = [
    'gemini-3.6-flash',
    'gemini-3.5-flash',
    'gemini-2.5-flash'
]

MODEL_NAME = None
gemini_contract_file = None

try:
    gemini_contract_file = client.files.upload(
        file=CONTRACT_PATH,
        config=types.UploadFileConfig(
            display_name='LegalLens Original Contract',
            mime_type='application/pdf'
        )
    )
    print('✅ تم تحميل النسخة الأصلية إلى جلسة Gemini بنجاح.')
except Exception as e:
    raise RuntimeError(f'❌ فشل تحميل العقد إلى Gemini: {e}')

# اختيار أول نموذج متاح فعليًا دون إرسال أسئلة للمستخدم
for candidate in SUPPORTED_MODELS:
    try:
        test = client.models.generate_content(
            model=candidate,
            contents='رد بكلمة واحدة فقط: جاهز',
            config=types.GenerateContentConfig(temperature=0.0, max_output_tokens=10)
        )
        if test and getattr(test, 'text', None):
            MODEL_NAME = candidate
            break
    except Exception as e:
        msg = str(e)
        if '429' in msg or 'RESOURCE_EXHAUSTED' in msg:
            # لا نختبر نماذج إضافية إذا كان الحساب نفسه على حد الطلبات.
            MODEL_NAME = candidate
            print(f'⚠️ تم اختيار {candidate} مع وجود Rate Limit حالي؛ سيُستخدم retry تلقائيًا عند السؤال.')
            break
        continue

if MODEL_NAME is None:
    MODEL_NAME = 'gemini-3.6-flash'

print(f'🤖 النموذج المستخدم: {MODEL_NAME}')
print('🔒 مصدر المعرفة: العقد الأصلي فقط.')

# 5) منطق الشات بوت — إجابة دقيقة من العقد الأصلي فقط

SYSTEM_INSTRUCTION = '''
أنت LegalLens، مساعد لتحليل العقد المرفوع.

قواعد إلزامية:
1) المصدر الوحيد للإجابة هو ملف العقد الأصلي المرفق في الطلب. لا تستخدم الإنترنت ولا المعرفة العامة ولا التخمين.
2) افهم السؤال حتى لو كان مكتوبًا بلهجة مصرية أو بصياغة مختصرة، ثم ابحث عن الإجابة داخل العقد.
3) عند السؤال عن شخص أو طرف أو مبلغ أو رقم شقة/عمارة/دور أو تاريخ أو مدة أو بند، اقرأ الموضع المناسب من العقد بعناية شديدة، ولا تغيّر أي رقم.
4) إذا كانت المعلومة موجودة في العقد، أجب عنها بوضوح وبالعربية، ويمكنك إعادة صياغة الجملة لتكون مفهومة، لكن لا تغيّر معناها أو أرقامها.
5) إذا كانت الإجابة موزعة على أكثر من موضع في العقد، اجمع المعلومات الموجودة في العقد فقط وقدّم إجابة واحدة مرتبة.
6) إذا كان السؤال يتطلب استنتاجًا غير مذكور صراحة في العقد، لا تخمّن. قل: «❌ إجابة هذا السؤال غير موجودة في العقد المرفوع.»
7) إذا سأل المستخدم عن حكم قانوني عام أو معلومة خارج العقد، لا تجب من معرفتك العامة؛ قل: «❌ إجابة هذا السؤال غير موجودة في العقد المرفوع.»
8) إذا كان السؤال خارج موضوع العقد تمامًا، قل: «❌ هذا السؤال خارج نطاق العقد المرفوع.»
9) لا تدّعي أن شيئًا موجود في العقد إذا لم تجده بوضوح.
10) عند وجود أكثر من قيمة متشابهة، ميّز بينها حسب السياق بدل اختيار قيمة عشوائية.
11) اجعل الإجابة مباشرة ومفيدة، ولا تكتب شرحًا تقنيًا عن النموذج أو الـ RAG.
12) في نهاية الإجابة، إذا أمكن تحديد الموضع، أضف: «📄 الصفحة: X».
'''

chat_history = []

def generate_answer(question, max_retries=4):
    question = (question or '').strip()
    if not question:
        return '⚠️ اكتب سؤالًا أولًا.'

    prompt = f'''\
أجب عن السؤال التالي باستخدام العقد الأصلي المرفق فقط.

سؤال المستخدم:
{question}

لا تعتمد على أي معلومة خارج الملف المرفق.
'''

    contents = [gemini_contract_file, prompt]

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=contents,
                config=types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION,
                    temperature=0.0,
                    max_output_tokens=1200,
                )
            )

            answer = (getattr(response, 'text', '') or '').strip()
            if answer:
                chat_history.append((question, answer))
                return answer
            return '❌ إجابة هذا السؤال غير موجودة في العقد المرفوع.'

        except Exception as e:
            msg = str(e)
            rate_limited = ('429' in msg or 'RESOURCE_EXHAUSTED' in msg or 'quota' in msg.lower())
            if rate_limited and attempt < max_retries - 1:
                wait_seconds = 8 * (2 ** attempt)
                time.sleep(wait_seconds)
                continue

            if rate_limited:
                return '⚠️ تم الوصول إلى حد طلبات Gemini مؤقتًا. انتظر قليلًا ثم أرسل السؤال مرة أخرى.'
            return f'⚠️ حدث خطأ أثناء معالجة السؤال: {msg}'

    return '⚠️ تعذر الحصول على إجابة حاليًا.'

print('✅ منطق الشات بوت جاهز.')

# 6) واجهة الشات بوت النهائية

output_area = widgets.Output(layout=widgets.Layout(
    border='1px solid #ddd', padding='10px', width='100%'
))

title = widgets.HTML('''
<div style='direction:rtl;text-align:right;padding:16px;border-radius:12px;background:#f5f7fb;margin-bottom:12px;'>
  <h2 style='margin:0 0 8px 0;'>📄 LegalLens — مساعد العقد</h2>
  <div>🔒 الشات بوت يعتمد على <b>العقد الأصلي المحفوظ مسبقًا في Google Drive</b> فقط.</div>
  <div style='margin-top:5px;color:#666;'>لا تحتاج إلى رفع العقد مرة أخرى. اسأل عن أي معلومة موجودة في العقد.</div>
</div>
''')

question_box = widgets.Textarea(
    placeholder='اكتب سؤالك عن العقد هنا...',
    layout=widgets.Layout(width='80%', min_height='70px'),
    style={'description_width': 'initial'}
)

send_button = widgets.Button(
    description='🔍 إرسال',
    button_style='primary',
    layout=widgets.Layout(width='18%', height='70px')
)

def show_message(role, text):
    safe = html.escape(str(text)).replace('\n', '<br>')
    if role == 'user':
        box = '#e8f0fe'
        label = '👤 أنت'
    else:
        box = '#f1f3f4'
        label = '🤖 LegalLens'
    with output_area:
        display(HTML(f'''<div style='direction:rtl;text-align:right;margin:10px 0;'>
        <div style='font-weight:bold;margin-bottom:5px;'>{label}</div>
        <div style='background:{box};padding:12px;border-radius:10px;line-height:1.8;'>{safe}</div>
        </div>'''))

def process_query(_=None):
    question = question_box.value.strip()
    if not question:
        return
    question_box.value = ''
    show_message('user', question)
    answer = generate_answer(question)
    show_message('bot', answer)

send_button.on_click(process_query)

display(title)
display(widgets.HBox([question_box, send_button]))
display(output_area)

print('✅ الشات بوت جاهز لاستقبال الأسئلة.')